title = "Notre-Dame de Paris"
baseURL = "https://gohugo-theme-ananke.pages.dev"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
resourceDir = "./resources"


[[module.imports]]
  path = 'github.com/gethinode/hinode'
[[module.imports]]
  path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'
  version = "v2.12.2"
